### PR TITLE
Fix PR #2399

### PR DESCRIPTION
**Pull request by nitriques**
This should close #2399

### CODE REVIEW

**Comment by jensscherbl** [comment]
> Since I am the one who told @beaubbe to push against integration, I will open a new PR.

Great. But give the PR a little time to be tested and verified by others before merging. Maybe @nilshoerrmann can also comment on this to make sure it didn't have any unwanted side effects.

**Comment by nitriques** [comment]
> Great. But give the PR a little time to be tested and verified by others before merging.

We did test it a lot. And I do not merge any of my own code anymore ;)

But yeah if @nilshoerrmann has the time to test/check it's always good.

**Comment by nitriques** [comment]
@brendo Why did you closed ?

**Comment by brendo** [comment]
Incomplete fix (missing minified CSS) and also both #2399 and #2406 should be resolved. I believe that 85e89930d52b173e6a6d051e852e0cfe89aff029 does this.

**Comment by nitriques** [comment]
Yup!

**Pull request closed without merging**
