### PR TITLE
Move to data-attributes in the backend admin pages instead of using classes

### PR DESCRIPTION
**Pull request by brendo**
This pull request changes the way we interact with the Administration `$context`. Instead of the context (which is the URL path items) being added blindly as classes to the `<body>`, they are now added as `data-attributes` as suggested in #2311. If the value is an array, it will be JSON encoded (which fixes an existing bug with associations appearing as `associations-Array`).

To further address #1585, the `Administration->getPageCallback()` has been educated about:

- `/blueprints/pages/`
- `/blueprints/events/`
- `/blueprints/datasources/`
- `/blueprints/pages/`

These pages now reference the following path: `/blueprints/events/edit/add_date/saved/` with named parameters instead of just indexed:

- `action`: edit
- `handle`: add_date (for pages & sections, this will be named `id`)
- `flag`: saved

As part of this change, the CSS classes have been cleaned up and the references to `$this->context[0]` (etc) have been updated to reflect the new named parameters.

This change will have an impact on any extension that:

- Relies on `$this->_context` for any of the blueprint pages (PHP)
- Relies on any of those context items being available as a class (either in PHP or JS)

I think it's a worthwhile break, as it's now less magical for extensions!

CC in original bug reporters: @nilshoerrmann, @designermonkey

### CODE REVIEW

**Comment by designermonkey** [comment]
:+1:

**Comment by nitriques** [comment]
:+1:

**Comment by nilshoerrmann** [comment]
:+1:

**Comment by jensscherbl** [comment]
:+1:

**Comment by brendo** [comment]
The logic for actually parsing the 'extras' of a URL shouldn't really sit in the `Administration` class. The `AdministrationPage` class is a much better place for this logic as pages can then parse the URL however they wish and create their owned named context.

So acting on this, I've made dc189a0. The logic for the Publish, Authors, Events, Datasources, Pages and Sections context has moved to the relevant classes into a `parseContext` method and out of the `Administration` class.

This is a funny example of how extensions have had more power than the core. Extensions already have access to the `AdminPagePostCallback` delegate, which allows the context to be overridden as they see fit. The addition of `parseContext` means that extensions which provide multiple pages can override the context in a more convenient fashion instead of having to do conditional logic on `$page` inside the delegate callback.

There is still some extra cleanup that can be done for the`/login` route as well as enforcing the fix for #2367 before I'd merge this change.

Anyone spot anything odd yet?

**Comment by brendo** [comment]
This now includes @nitriques fix to check that Extensions are enabled before routing to them. I'm in a position to merge this into `integration` now as long as everyone is happy :)

**Comment by nitriques** [comment]
Yeah!!!

**Pull request merged**
