### PR TITLE
Z-index problems with nav

### PR DESCRIPTION
**Pull request by beaubbe**
added z-index to structure ul so that it does not overlap content ul in the nav.
image

### CODE REVIEW

**Comment by nitriques** [comment]
I would also port this to 2.6.x.

**Comment by jensscherbl** [comment]
@beaubbe Can you please resubmit this against the `2.6.x` branch?

**Comment by nitriques** [comment]
@jensscherbl I think this fix should go in both branches. What's the prefered way for this ? Submitting against 2.6.x ?

**Comment by jensscherbl** [comment]
> I think this fix should go in both branches.

Yes, sure.

> What's the prefered way for this ? Submitting against 2.6.x ?

Yes. Patches should be submitted against `2.6.x`. `2.6.x` will then be merged with `integration` after release to make sure that `integration` receives all patches as well.

**Comment by nitriques** [comment]
Ok perfect. Since I am the one who told @beaubbe to push against integration, I will open a new PR.

**Comment by jensscherbl** [comment]
Resubmitted against `2.6.x` in #2402. Closing.

**Pull request closed without merging**
