### PR TITLE
Fix "secure" flag on cookies; fixes #2627

### LINKED ISSUE #2627: Symphony never sets the "secure" flag on cookies
Due to a typo in `class.cookie.php`, Symphony never sets the "secure" flag on cookies/sessions. (It is supposed to do this in SSL environments.)

Here are the lines in question:

``` php
if (defined(__SECURE__)) {
    $this->_secure = __SECURE__;
}
```

The fix is to add the missing (single) quotes:

``` php
if (defined('__SECURE__')) {
    $this->_secure = __SECURE__;
}
```

I can provide a pull request. To which branch should I send it?

### PR DESCRIPTION
**Pull request by michael-e**
I suggest to also backport this fix to the 2.6.x branch.

### CODE REVIEW

**Comment by michael-e** [comment]
@brendo, please don't forget to cherry-pick this commit for 2.6.x

**Comment by nitriques** [comment]
@michael-e See 382e446. But I'd rather focus on shipping 2.7.0 instead of this. But I can help if you can produce a new 2.6.x bundle.

**Comment by michael-e** [comment]
Well, I never created a new Symphony bundle, and I am afraid that my time is too limited to dive into that. Maybe @brendo can help?

**Comment by nitriques** [comment]
Thanks Brendan. Ping me and I'll add it on the website (but I think you still can do it yourself)

**Comment by brendo** [comment]
@nitriques All done, 2.6.8 is released, tagged and added to the Symphony website. As there is no documentation changes you can get away with copying 2.6.7 docs and renaming the folder ;)

**Comment by nitriques** [comment]
Perfect, will do. Ping me on twitter if I forget! Thanks.

**Comment by nitriques** [comment]
And let me merge in 2.6.8 in  2.7.0 ;)

**Pull request merged**
