### PR TITLE
Default Value jQuery plugin 

### LINKED ISSUE #2511: DS/Event Editor: fill name with the target section name if empty
I feel like this would save me a lot of time. What about you ?

### PR DESCRIPTION
**Pull request by nitriques**
This commit introduce a new jQuery plugin called Default Value, which
gives a input a source element to value its value from, when a specified
event occurs on this source element.

This behaviour is switched to off when the users focuses on the input
field and then blurs out, leaving a value in the input.

This commit also hooks this behaviours on the Data Source name input and
on the Event name input.

Closes #2511

### CODE REVIEW

**Comment by nitriques** [comment]
rebased.

**Comment by nitriques** [comment]
@brendo Would this be ok for 2.6.4 (even if it's a new feature). I'd like to use it!

**Comment by nitriques** [comment]
Anybody had the chance to test it ?

**Comment by jensscherbl** [comment]
> Would this be ok for 2.6.4 (even if it's a new feature)

You be the judge... ;)

> Given a version number MAJOR.MINOR.PATCH, increment the:
> 
> MAJOR version when you make incompatible API changes,
> MINOR version when you add functionality in a backwards-compatible manner, and
> PATCH version when you make backwards-compatible bug fixes.

**Comment by nitriques** [comment]
:) I'll wait then. But 2.7.0 will be released fast, count on me for that.

**Comment by jensscherbl** [comment]
> But 2.7.0 will be released fast, count on me for that.

No problem with that.

**Comment by nitriques** [comment]
> No problem with that.

Great. I do not mind release 2.7.1 early either, if necessary. I,ll package 2.6.4 tomorrow.

**Comment by nitriques** [comment]
Manually merged in 0e27ff5

**Pull request closed without merging**
