### PR TITLE
Add data-attributes to publish filtering interface

### PR DESCRIPTION
**Pull request by twiro**
This PR introduces data-attributes to the publish filtering interface. This allows for better and more precise and flexible handling of comparison modes and their help texts.

It also removes the (annoying) leading whitespace in the input fields of publish filtering interface.

See https://github.com/symphonycms/symphony-2/issues/2499 for details.

### CODE REVIEW

**Comment by nitriques** [comment]
At first glance, it seems ligit. I'll test ASAP. Thanks!

**Comment by nitriques** [comment]
Did you tested it with some of the most used extensions ?

**Comment by twiro** [comment]
> _Did you tested it with some of the most used extensions ?_

You bet I did :)

As I noticed lots of little quirks and bugs in Publish Filtering (mostly related to special charactes and umlauts) while testing my changes I had to reassure that they weren't caused by anything I did - so I started testing really intensely and documented my results for both cases - before my changes and after - they both were exactly the same except for the one scenario I wanted to fix (the "between"-filter in the Publish Filtering Interface).

I posted about this [here](https://github.com/symphonycms/symphony-2/issues/2564) and documented my filtering results in an [own repo](https://github.com/twiro/symphony-filtering-tests).

My changes won't do much to fix most of the issues Publish Filtering has, but nonetheless they're fixing a basic conceptual flaw and at least will make the [last four failed test cases in number field](https://github.com/twiro/symphony-filtering-tests/blob/master/fields/number-field.md) disappear! 

(Though the number field extensions needs to be fixed for that too - will do so after this change has been released!)

**Comment by nitriques** [comment]
> You bet I did :)

:+1: 

> I posted about this here and documented my filtering results in an own repo.

This is really nice thanks.

I'll test ASAP.

**Pull request merged**
