### PR TITLE
Association filters

### PR DESCRIPTION
**Pull request by jonmifsud**
Opening PR to continue the discussion on #2322 as is the PR is missing an update to add the `filters` field to the associations table.

In conjunction with this there are PR's on the respective association field components, which make use of the filtering. [Association UI Selector](https://github.com/hananils/association_ui_selector/pull/44) and [Association UI Editor](https://github.com/hananils/association_ui_editor/pull/26)

I do think there might be a bit more work required and adjustments but would be good to have someone try it out for feedback at this stage.

### CODE REVIEW

**Comment by jensscherbl** [comment]
![screen shot 2015-03-24 at 13 39 27][2]

Scrutinizer says you [introduced new issues and made a few things worse][1]. Should be addressed before merging.

Also has to be rebased, I guess?

[1]: https://scrutinizer-ci.com/g/symphonycms/symphony-2/inspections/acbfe0fe-fd91-4925-8f03-4ad1b9dabb13

[2]: https://cloud.githubusercontent.com/assets/1640033/6801812/75c81d84-d22b-11e4-92dd-6265e1dcdf9a.png

**Comment by jonmifsud** [comment]
Thanks for the heads up never really noticed it highlights issues. I did
rebase recently but I wouldn't be surprised if there are a few more changes.

A couple of them mention the use of $_REQUEST or $_GET parameters - which
is the way things were before (rather than fixes they were moved
elsewhere), not sure if I can fix those. I should be able to clean up
everything else though.

**Comment by jonmifsud** [comment]
@brendo not sure if you've looked into this yet, any more pointers on the implementation? I'll probably be merging this in another project in the coming days so would be a good time to do any changes.

**Comment by nitriques** [comment]
> A couple of them mention the use of $_REQUEST or $_GET parameters

Make sur to ALWAYS call General::sanitize or MySQL::cleanValue each time you read from those.

**Comment by nitriques** [comment]
Closing in favor of #2565

**Pull request closed without merging**
