### PR TITLE
Added root-dir parameter

### PR DESCRIPTION
**Pull request by nitriques**
Now that Symphony can be installed in subfolder, I need to be able to get that subfolder without the domain attached to it.

So I've splitted up the DOMAIN constant to create the DIRROOT constant that contains only the basename of PHP_SELF.

DOMAIN does not change values, so this is not a breaking change.

### CODE REVIEW

**Comment by nitriques** [comment]
I never understood why $root did contain the domain name + folder. I would really like to have it in the core.

I know I can always add it via an extension, but I feel like to would encourage developers to drop $root and use $root-dir.

Using the full url (with protocol + domain name) is not a good practice IMHO. That's why I think it should be in the core.

**Comment by munki-boy** [comment]
+1 won't need to substring sometimes.

**Comment by nitriques** [comment]
> won't need to substring

Yes. Substring really is not a good practice.

**Comment by munki-boy** [comment]
especially substring-before(substring-after) just to get the folder name on its own.

**Comment by nitriques** [comment]
> especially substring-before(substring-after) just to get the folder name on its own.

especially considering the value IS ALREADY separated before constructing root.

@jensscherbl Are we planning 2.6.4 ? I do not really mind releasing more often. Would you still want 2.7 or we go strait to 3.0.0 ?

**Comment by jensscherbl** [comment]
> Are we planning 2.6.4?

Yes.

> I do not really mind releasing more often. Would you still want 2.7 or we go strait to 3.0.0 ?

But the addition you proposed is not a bugfix, so that would be a `2.7.0` release.

**Comment by nitriques** [comment]
> But the addition you proposed is not a bugfix, so that would be a 2.7.0 or 3.0.0 release.

Ok let's do it for 2.7.0 then.

**Comment by nitriques** [comment]
Manually merged in `2.7.x`

**Pull request closed without merging**
