### PR TITLE
Refactor EntryManager::edit() and EntryManager::add() to make them identical in terms of field data saving

### PR DESCRIPTION
**Pull request by nitriques**
The title says it all ! + check the commits messages

157b716 also fixes a bug introduced in #2678 .

### CODE REVIEW

**Comment by jonmifsud** [comment]
@nitriques any specific reason we need the lock table here?

Finding quite a few instances where mysql seems to be getting stuck on a lock for one of the sites we're running.

**Comment by michael-e** [comment]
Locking tables when editing entries has solved https://github.com/symphonycms/symphony-2/issues/2472 — Symphony actually had a race condition without these locks.

**Comment by jonmifsud** [comment]
@michael-e thanks for that. I had to disable it on a couple of sites it seems to have adverse effects in some scenarios. 

Entries where at times taking over 60s to save since a switch to cloudfront today; the client was complaining that they are getting 504s likely this has been the case for a long time and our timeout on varnish was more lenient. 

Since the change it saves in 2s or less. Other than that the lock was obviously also blocking frontend performance at times...

I'm guessing in symphony 3 this would be a transaction rather than a lock. A lock doesn't seem to make logical sense; in that my understanding is we are using it instead of a transaction to ensure it is successfully completed at one go correct?

**Comment by michael-e** [comment]
Sounds bad. But honestly, I never had any issues with table locking.

> I'm guessing in symphony 3 this would be a transaction rather than a lock.

Hmmm, I think so, but I am not sure.

**Pull request merged**
