### PR TITLE
Add curl_error message

### PR DESCRIPTION
**Pull request by nitriques**
This caught my attention: curl_error actually contained the curl_errno

Since it confusing, this aligns things with how curl names things

### CODE REVIEW

**Comment by brendo** [comment]
Just flagging a dependency on [Remote Datasource](https://github.com/symphonycms/remote_datasource/blob/master/data-sources/datasource.remote.php#L139) for this change :)

**Comment by brendo** [comment]
And you also have #2544 as well? Duplicate?

**Comment by nitriques** [comment]
> Just flagging a dependency on Remote Datasource for this change :)

Oh ok thanks!

> And you also have #2544 as well? Duplicate?

Ah damn yes.

**Comment by nitriques** [comment]
This is postpone to 3.0.0 has it is a breaking change, sadly.

**Comment by nitriques** [comment]
Remote Datasource has been taken care of

**Pull request merged**
