### PR TITLE
Symphony 2.6: Remove calendar widget

### PR DESCRIPTION
**Pull request by nilshoerrmann**
Due to timezone problems (see #2312), this pull request removes the new calendar widget again.
It should be fixed and reapplied in https://github.com/symphonycms/symphony-2/tree/calendar (Symphony 2.7, if possible).

### CODE REVIEW

**Comment by brendo** [comment]
Am I right in saying that the only reason we are removing this is because of the Feature Request to adjust the start of the week? This FR led to incorrect calendar rendering when combined with a system language that is not English.

Is it possible to just revert the FR and leave the calendar as is? Do the timezone issues affect the calendar otherwise?

**Comment by nilshoerrmann** [comment]
No, the feature request has been added and is working as intended. The problem is that the calendar shifts days one weekday back depending on your timezone.

This issue was found while adding the week offset but it exists indepently.

**Comment by brendo** [comment]
Can you provide a exact set of steps to replicate?

**Comment by nilshoerrmann** [comment]
There aren't any specific steps, it's more the general setup:

- German OS (in my case Mac OS X Yosemite)
- German locales in the browser (in my case Firefox 35 with `Deutsch [de]` as primary language)
- German date and time (in my case CET which is `UTC+1`)

In this given setup, using the calendar will result in the first January starting on the wrong day (Wednesday instead of Thursday).

**Comment by brendo** [comment]
Ok, well I think this may be fixed then:

- German Timezone in OS (Europe/Berlin)
- German Timezone in Symphony (Europe/Berlin)
- German Language set in Firefox/Chrome (`de`)

Creating a new entry, and flipping the calendar back to Januar 2015 results in the 1st being on Donnerstag, which is correct. Care to give `integration` a try and see if you can replicate?

**Comment by nilshoerrmann** [comment]
I'll have a look later today (having a sick child around might delay that a bit).

**Comment by brendo** [comment]
Ah that's no good! Hope you're still getting some sleep :)

**Comment by nilshoerrmann** [comment]
I just checked and I can confirm that the calendar displays date/weekday connections correctly. 

> Ah that's no good! Hope you're still getting some sleep :)

Max is sleeping most of the time, so we get sleep as well. Nothing serious.

**Comment by nilshoerrmann** [comment]
Revisiting this issue, I ask myself [how your changes to the to the calendar script might have fixed the issue](https://github.com/symphonycms/symphony-2/commit/57fda1f7e7b3ccd8a472f56747d60b82b03e29ec#diff-5c17bd4c69c458c61cfae7b3cc4c4984R152): it should work even without these changes.

I've got an idea (and I'd like @animaux to check this as well): Is it possible that the turn of the year fooled us and that we looked as January 20**14** which of course started on a Wednesday.

**Comment by nilshoerrmann** [comment]
This pull request has been rendered obsolete by https://github.com/symphonycms/symphony-2/commit/57fda1f7e7b3ccd8a472f56747d60b82b03e29ec#commitcomment-9540637.

**Comment by animaux** [comment]
@nilshoerrmann 

> Is it possible that the turn of the year fooled us and that we looked as January 2014 which of course started on a Wednesday.

Definitely not. I double- and triplechecked.

**Pull request closed without merging**
