### PR TITLE
Remove backticks from field table name

### PR DESCRIPTION
**Pull request by designermonkey**
As per #2422

### CODE REVIEW

**Comment by brendo** [comment]
@nitriques I know this was originally added by you for consistency with `insert()` and `update()` methods, but with PDO it looks like it's not required and it's merely used as a best practice.

**Comment by nitriques** [comment]
> it's merely used as a best practice.

Even if the table names contains weird characters ? Wasn't this the goal ? 

Anyhow, less if more so I am all up for this ! But we should do it everywhere, not only on a single statement....

**Comment by michael-e** [comment]
I don't get this. I always thought that backticks – even if they may not be required – won't cause any issues. Why have they been removed here?

**Comment by designermonkey** [comment]
PDO will automatically wrap table and column names with backticks, so providing them only causes an error, as a table would be double wrapped.

**Comment by michael-e** [comment]
Aha, thanks! So the backticks should probably be removed everywhere, correct?

**Comment by designermonkey** [comment]
only in the table names passed through. in the rest of the queries, they can either be there or not. I was only error-preventing here.

**Comment by nitriques** [comment]
Ok Thanks John.

**Pull request merged**
