### PR TITLE
Rebase `2.7.x` on `2.6.x`

### PR DESCRIPTION
**Pull request by jensscherbl**
I think there's something weirdly fucked up with our branches. Couldn’t do a clean rebase, so a merge seemed to be the more practical solution here. Any ideas?

### CODE REVIEW

**Comment by nitriques** [comment]
Hey @jensscherbl I want to merge all 2.7.x PR before doing so, to minimize conflict resolution. Also, I'd like to try git imerge in order to preserve history. But thanks!

**Comment by jensscherbl** [comment]
Ok. But why is `2.7.x` behind `2.6.x` in the first place, and why can't it be rebased properly? Even after  resolving all conflicts when doing a rebase, the rebased branch can't be pushed or merged without merging `2.7.x` back into it. Seems pretty odd to me.

**Comment by jensscherbl** [comment]
Btw., is there anything else I can help with at the moment?

**Comment by nitriques** [comment]
> But why is 2.7.x behind 2.6.x in the first place, 

Because we had to release hot fixes for the 2.6.x release line after the work on 2.7.x was well started.

> can't be pushed or merged 

Rebase is rewriting history, which is something that does not work very well when collaborating (sadly).

If you can't `git pull upstream 2.7.x --ff-only` the best thing is to `git checkout <any-other-branch>`, `git branch -D 2.7.x`, `git checkout -b 2.7.x upstream/2.7.x`.

But rebases removes a lot of unwanted commits (like optional merge commits) and makes reading the history (and doing git bisect) much much easier.

**Comment by nitriques** [comment]
> Btw., is there anything else I can help with at the moment?

Absolutely ! You could test PRs with the Testing needed label.

To checkout prs, you can do

```
git fetch upstream pull/<issue id>/head:pr-<issue-id>
git checkout pr-<issue-id>
``` 

I've written a bash function to do it

```
# git checkout pull request
# usagage: gcopr upstream 22
function gcopr {
  git fetch $1 pull/$2/head:pr-$2
  git checkout pr-$2
}
```

**Comment by nitriques** [comment]
Example: https://github.com/symphonycms/symphony-2/pull/2680 ;)

**Comment by nitriques** [comment]
https://github.com/symphonycms/symphony-2/pull/2659 Also!

**Comment by jensscherbl** [comment]
Kinda missed your reply, sorry.  Will test the rebased and merged `2.7.x` branch over the next couple of days.

**Comment by nitriques** [comment]
Great. The `2.7.x` branch has been rebased on top of master so we are no missing anything ;)

**Pull request closed without merging**
