### PR TITLE
Replace custom logging with Monolog

### PR DESCRIPTION
**Pull request by brendo**
This implements #2223 for the `integration` branch. It's a great step forward, although there's still more to do to allow easier configuration.. stay tuned.

### CODE REVIEW

**Comment by brendo** [comment]
Probably best to merge #2570 first, as I rebased off that work ;)

**Comment by nitriques** [comment]
Awesome!

**Comment by brendo** [comment]
Perfecto, next stop config files

**Comment by nitriques** [comment]
This also opens the path to installing extensions with composer (I mean downloading it)

**Comment by brendo** [comment]
> This also opens the path to installing extensions with composer (I mean downloading it)

Yep, the path I'm currently heading down is making composer be able to install Symphony, so we run Symphony in a CI environment...

**Comment by nitriques** [comment]
That would be awesome.

I often dream about splitting the core across multiple module :+1:

**Pull request merged**
