### PR TITLE
[don't merge] symphony docs (gh-pages)

### PR DESCRIPTION
**Pull request by bernardodiasc**
This PR isn't ready but have useful information for anyone interested in help. Please read the discussion bellow. 

__Status:__ gathering information.

__Goal:__ use GitHub to host docs.getsymphony.com with gh-pages, all content should be markdown.

__Preview:__ http://avanteweb.github.io/symphony-2/

### CODE REVIEW

**Comment by bernardodiasc** [comment]
While gathering all material, found a huge amount of fragmented resources:

- https://github.com/symphonycms/wg
- https://github.com/symphonycms/docs.getsymphony.com
- https://github.com/symphonycms/getsymphony-html
- https://github.com/symphonycms/symphony-next/issues (not sure if it's relevant)
- https://github.com/symphonycms/docs_getsymphony
- https://github.com/symphonycms/docs
- https://github.com/symphonycms/sym-getsymphony
- http://www.getsymphony.com/discuss/thread/29060/
- http://www.getsymphony.com/discuss/thread/48028/
- http://www.getsymphony.com/discuss/thread/100339/
- there is more in learn, articles and forum sections...
- there is good articles around the web...

I'll read, review and organize everything, this may take a some time. Advices about these resources are welcome (some have 3 years old).

@brendo can you confirm if the goal is use GitHub to host docs.getsymphony.com with gh-pages? There is a lot work done by @bauhouse that we need to use (good stuff!).

@ijy I'll vote for the simplest way to have markdown transformed in the Factory site. Git hooks seems a nice way to make it work with Gulp. I can use a little help on this :)

Cheers

**Comment by brendo** [comment]
> @brendo can you confirm if the goal is use GitHub to host docs.getsymphony.com with gh-pages? There is a lot work done by @bauhouse that we need to use (good stuff!).

Yes that has been a goal of mine for awhile, simply because it reduces the barrier of entry and takes the load off a single person. If anyone can submit pull requests to the docs to fix typos or clarify terms then it should led to more relevant and engaging documentation.

The reason why I've wanted to use Jekyll is because of that instant deployment. We don't need a single person to merge the request, run Gulp and then deploy the code. It's automagically done by Github. I realise this is not the most flexible approach, but I think the time savings given our limited resources make it a worthwhile goal. @ijy highlights some things that I wasn't aware of though. If webhooks can magically do the same thing, be my guest (but we'll definitely need your help getting that all setup!)

**Comment by johnpuddephatt** [comment]
@bernardodiasc I have both the time and the inclination to help with this :)

**Comment by brendo** [comment]
Thanks for the offer @johnpuddephatt and @bernardodiasc :)

**Comment by bernardodiasc** [comment]
Awesome. Let's keep the goal on focus and then we can choose the best method/tool to accomplish this.

@johnpuddephatt thanks mate, lets do this!

I think the priority here is gather all good content and save in markdown files in a organized way. We can use this repo https://github.com/symphonycms/wg (can we?) to accomplish this fisrt task (content only). And then bring to official `gh-pages` with Factory and all goods.

Started reviewing the Book from WG and did a single-page doc using [`inline-docs`](https://github.com/joshwnj/inline-docs/), you can check it here http://bernardodiasc.github.io/wg/book/. With this tool I can easily review everything and make corrections on headers hierarchy.

John, you can reach me by email (bernardodiasdacruz @ gmail.com) to align the efforts.

**Comment by bernardodiasc** [comment]
All content from https://github.com/symphonycms/wg migrated to Symphony Docs.

After spent a considerable time wondering about this, Jekyll is not bad after all, here is the working preview http://avanteweb.github.io/symphony-2/

**Comment by johnpuddephatt** [comment]
`The reason why I've wanted to use Jekyll is because of that instant deployment`

@brendo, you'll be pleased to know that's what we now appear to have – pull requests can be submitted (directly through the github site if desired, making the barrier to entry super low) and upon merging the documentation site is immediately updated.

**Comment by brendo** [comment]
> @brendo, you'll be pleased to know that's what we now appear to have – pull requests can be submitted (directly through the github site if desired, making the barrier to entry super low) and upon merging the documentation site is immediately updated.

Awesome! How about I add you both to the [https://github.com/symphonycms/docs_getsymphony](https://github.com/symphonycms/docs_getsymphony) repo so we can start to get the ball rolling on this? @bauhouse, do have any objections to this approach (I feel horrible for replacing your hard work!)? @johnpuddephatt @bernardodiasc, would you be happy to work within that repo?

**Comment by bernardodiasc** [comment]
As mentioned, I'm wondering about how to accomplish this for a while. Always focusing on the easiest way for newcomers to setup and contribute. Tried more than 3 ways so far, and not counting https://github.com/symphonycms/docs_getsymphony and https://github.com/symphonycms/getsymphony-html. These two approaches are very interesting and might work like the Gulp way (webhooks), but didn't test yet how behaves with markdown files.

In fact what tipped the balance for Jekyll is mostly because is a GitHub tool to use in GitHub, and this is pretty much what we want. On the other hand is an entirely different enviroment (yaml, ruby, markdown files, custom template engine similar to Twig). I ended accepting the fact that this is not a showcase project, it's just a documentation place, the king here is the content and thats it. And the content here is markdown, period.

Even if the Jekyll has surprised me positively, I am always open to try some more "symphonish" approach. But now kinda need to beat the easiness of Jekyll, this means a setup that we'll only touch markdown files.

We are collecting all work done in docs subject from a lot developers, trying to save all efforts invested. Can't say "thanks" enough!

@brendo what about this one https://github.com/symphonycms/docs.getsymphony.com?

**Comment by brendo** [comment]
I have no idea, I'd go with the latter though. We should be able to use Github's automatic features to get that resolving as well :) Ideally I think we should delete all branches except for a `gh-pages` branch to keep it clean and simple.

Once again, thanks for your efforts! You can document the Jekyll process in the docs ;)

**Comment by bernardodiasc** [comment]
Nice, anytime. Now just need write permission on the repo. :)

**Comment by tachyondecay** [comment]
This looks great. I like writing documentation! I’m going to keep an eye on this, and once the repo is up and running, hopefully I can find time to contribute.

**Comment by brendo** [comment]
Invites sent, you should be ready to rock and roll.

**Comment by bernardodiasc** [comment]
:metal:

Hmm, double checking, docs_getsymphony or docs.getsymphony.com? (sorry, not clear, maybe my english is fooling me)

**Comment by brendo** [comment]
You're invited to the Documentation team, which has access rights on both repos

**Comment by bernardodiasc** [comment]
Alright, I'll go for docs.getsymphony.com, its the conventional naming for kind of job. Asking this because it will be a gh-pages only, right? Better confirm before mess up :)

**Comment by brendo** [comment]
> Alright, I'll go for docs.getsymphony.com, its the conventional naming for this kind of job. Asking this because it will be a gh-pages only, right? Better confirm before mess up :)

Confirmed :)

**Comment by bernardodiasc** [comment]
https://symphonycms.github.io/docs.getsymphony.com/ :tada:

Moving on, closing this PR.

**Comment by nilshoerrmann** [comment]
Why don't you just rename the repo to `docs`. The Symphony domain might change (it did several times over the last years) and `docs` is pretty clear it the github context as well: the links would be https://github.com/symphonycms/docs and https://symphonycms.github.io/docs/. Straight forward.

**Comment by brendo** [comment]
Don't get hung up on the links, [we can change it](https://help.github.com/articles/setting-up-a-custom-domain-with-github-pages/) to `docs.getsymphony.com` pretty easily (with @allen's help)

**Comment by nitriques** [comment]
This is really great, props guys! :clap: :rocket: :guitar:

**Comment by ijy** [comment]
Sorry for the delay in comeback. Just noticing the flurry of activity on this one.

I don't see a problem with Jekyll being used for the docs. It may struggle if your static site requires a customised URL structure or functionality outside of the norm but in the case of simple documentation I don't see that being the case. For the Symphony documentation site I don't think we'd even be touching dates, categories, tags, pagination, or any other potentially tricky parameters in the URL so Jekyll should do the job. Content is the primary focus so whatever works best. 

Regarding the continuous delivery option, I mentioned it in case you particularly needed to go down the alternative route you mentioned with gulp. Specifically you can use the `post-receive` hook to trigger a remote build script on a server with the required tools and then deploy the built project to the hosting location of your choice (Github Pages or elsewhere). It's not magical in the sense that it does it all for you without instruction but git hooks can provide useful trigger points to latch on to in the process. :) It does add an extra step to the process so unless it's definitely needed then Jekyll will be one step simpler. 

It sounds like things are back to Jekyll now though with everything in place. Let the documenting begin! :)

**Pull request closed without merging**
