### PR TITLE
Update for prepopulate date field

### LINKED ISSUE #2541: Updater fails to fix Date Fields
There must have been a change in the Date Field somewhere between Symphony 2.3.6 anbd 2.6.5. Now, the `pre_populate` column can contain words like "now" and must be left empty if you don't want to pre-populate.

I updated some websites, and the former values "yes" and "no" were left in the database fields. Both will result in the current date being populated.

The updater should remove "no" values and replace "yes" with "now".

### PR DESCRIPTION
**Pull request by ChoboHub**
Fixes #2541

### CODE REVIEW

**Comment by nitriques** [comment]
LGTM.

@michael-e quick review if you can! @brendo would you have some other advice regarding the update code ?

Thanks guys.

**Comment by michael-e** [comment]
I am sorry, but I must keep away from GitHub and Gitter for some days. Too much work, hard times.

**Comment by nitriques** [comment]
No problems @michael-e, take your time.

**Comment by brendo** [comment]
Update code seems ok to me? Maybe missing a case for `null`?

**Comment by nitriques** [comment]
Merged as 334386b

**Pull request closed without merging**
