### PR TITLE
Use execute instead of grab

### PR DESCRIPTION
**Pull request by nitriques**
grab has been deprecated for sometime now. Time to move on.

@brendo is it ok to directly commit those kind of things in integration ?

### CODE REVIEW

**Comment by nitriques** [comment]
@brendo bump! :smile: I really think it's 2.6 scoped... cc @nilshoerrmann @jensscherbl

**Comment by brendo** [comment]
I'd like to keep this for 2.6.0. Removing would be a breaking change to any old installations, and we really shouldn't do that without a bump to 3.0.0

**Comment by nitriques** [comment]
Ok then!

**Comment by jensscherbl** [comment]
> Removing would be a breaking change to any old installations, and we really shouldn't do that without a bump to 3.0.0

Correct, removing has to wait for 3.0.0. But this commit should be fine for 2.6.0.

**Comment by jensscherbl** [comment]
> But this commit should be fine for 2.6.0.

Oh wait, this would affect existing datasources. My mistake.

**Comment by brendo** [comment]
This commit is only part of the puzzle:

- The base `DataSource` class still has a `grab()` function reference
-

**Comment by nitriques** [comment]
> The base DataSource class still has a grab() function reference

Was it fixed ? If not, leave the issue open I'll fix it.

**Pull request closed without merging**
