### PR TITLE
More url input sanitizing (for 2.5.x)

### PR DESCRIPTION
**Pull request by nitriques**
This commit prevents full path disclosure (and fatal errors) if the
mode or symphony-path $_GET values are not strings. Since symphony's
parses query[]= as strings, this check is required before any str*
calls.

This commit is a backport of 5762052 (see #2504)

### CODE REVIEW

**Comment by nitriques** [comment]
- [ ] Create a new migration for the new version, eg. 2.5.4 which should implement getVersion and getReleaseNotes methods
- Update the version constant in the project:
- [ ] package.json
- [ ] composer.json
- [ ] .htaccess (optional)
- [ ] install/index.php
- [ ] install/includes/htaccess.txt (optional)
- [ ] LICENCE (optional)
- [ ] symphony/assets/js/src/symphony.js (optional)
- [ ] Update the README.md file, replacing the version constant and updating any metadata as required
Create a commit, usually Release 2.5.4 and push to the corresponding branch. Testing at this point is recommended!
- [ ] Create an associated tag for the release, eg. 2.5.4

**Comment by brendo** [comment]
Well done @nitriques, congrats on your first 'release'! Is there anything I can help with?

**Comment by nitriques** [comment]
Nope thanks! https://github.com/symphonycms/symphony-2/releases/tag/2.5.4 :)

This one was pretty easy to do :)

And it's also live on the site: http://www.getsymphony.com/discuss/thread/111320/ I am doing 2.6.4 right now too!

**Comment by nitriques** [comment]
@brendo Ah! Uploading the doc via the FTP server, since I do not have access to it.

**Comment by nitriques** [comment]
And where should I upload the 'bundle' branch ? I can't find it on the website and older release just contains the core, not the bundle.

**Comment by brendo** [comment]
So historically, we used to have all the extensions in the `master` branch. This changed with `2.6` from memory and hence the `bundle` branch was created. `bundle` is essentially the latest release from `master` with the latest core extensions already included and it's used to generate the quick install zip that's provided by the website.

FTP information, let me dig around for that when I'm on my 'home' machine!

**Comment by nitriques** [comment]
Perfect,

Yes I understand the concept for the bundle branch, but can't find a zip that contains it on the website.

**Comment by brendo** [comment]
It's on the [release detail](http://www.getsymphony.com/download/releases/version/2.6.4/) pages, the download button :)

**Comment by nitriques** [comment]
@brendo I've check version 2.5.0 through 2.6.3: they all have an empty extension folder...

**Comment by brendo** [comment]
:cry: That is not intended. Oh dear. Let me have a look at the bundle script, there must be something missing it where it either doesn't check out the submodules, or it doesn't zip them. Great find!

**Comment by brendo** [comment]
Actually, I can't reproduce this. The downloads for 2.6, 2.6.1, 2.6.2 and 2.6.3 all include extensions in them?

**Comment by nitriques** [comment]
image

**Comment by nitriques** [comment]
The link I have points to github..

image

**Comment by nitriques** [comment]
But yeah, if I download them from the backend,

**Comment by brendo** [comment]
How very interesting. So the actual zip's from the backend contain the data, but the frontend links to Github... That explains a lot!

**Comment by nitriques** [comment]
Yup!

**Comment by nitriques** [comment]
Can you.... fix it ? :S

**Comment by brendo** [comment]
Not from where I am at the moment (work) but I'll take a look tonight!

**Comment by nitriques** [comment]
Yeah, no pressure. For me it's still the 29th here, so it's not even the day of the release hahah

**Comment by nitriques** [comment]
@brendo any updates?

**Pull request merged**
