### PR TITLE
simplify autoloader, embrace composer

### PR DESCRIPTION
**Pull request by jensscherbl**
Basically what I suggested in #2330.

Could reduce confusion and redundancy when it comes to autoloading (#2362).

### CODE REVIEW

**Comment by nitriques** [comment]
@jensscherbl We need to still support people who don't use it, am I right ?

**Comment by jensscherbl** [comment]
> @jensscherbl We need to still support people who don't use it, am I right ?

This is not about people using composer, this is about us using composer. I included the vendor folder in Symphony's versioning, so the composer autoloader is now just part of Symphony's code.

**Comment by nitriques** [comment]
Ok great. Let see what @brendo thinks. I am not against it.

**Comment by brendo** [comment]
If someone is already using Composer in their installation, or continues to use it after they do a base install, would committing the autoloader cause issues when future Symphony versions are released? My thoughts is the autoload files will have progressed with the additional classes and then our cut down autoload will result in a merge conflict?

**Comment by jensscherbl** [comment]
> If someone is already using Composer in their installation, or continues to use it after they do a base install, would committing the autoloader cause issues when future Symphony versions are released?

You mean if someone adds their own dependencies to Symphony's composer.json and vendor folder? 

Wouldn't be any different from changing any other of Symphony's core files. If you modify something and there are changes to these files in a new Symphony version, you need to readd your modifications after updating.

To be more specific, if you add dependencies via Composer, you need to delete your vendor folder, readd your custom dependencies and rerun `composer install` after updating.

The workflow doesn't change because of this pull-request.

**Comment by jensscherbl** [comment]
The only good argument I can think of against including the vendor folder in our repository is that it's generally not recommended because of redundancy. But on the other hand, Symphony is a standalone product, not a library, package or framework, so running composer locally to install dependencies shouldn't be a requirement to use the product.

**Comment by nitriques** [comment]
I agree with you Jens.

**Pull request merged**
