### PR TITLE
Fixed issue where windows paths broke xslimport

### LINKED ISSUE #2316: XSLT processor issue on Local Windows installs XAMPP and WAMP
Using integration branch to test local builds and have experienced an odd issue after install.. none of the XSLT processing transforms are working on frontend pages.

    XSLTProcessor::importStylesheet():
        compilation error: file file:///C:/xampp/htdocs/sym-git/ line 3 element import
        xsl:import : invalid URI reference C:\xampp\htdocs\sym-git/workspace/pages/home.xsl
    XSLTProcessor::transformToXml():
        No stylesheet associated to this object

### PR DESCRIPTION
**Pull request by jensscherbl**
Fixed issue where windows paths broke xslimport.

### CODE REVIEW

**Comment by nitriques** [comment]
@jensscherbl Why does the PAGES is not used anymore ?

**Comment by jensscherbl** [comment]
> Why does the PAGES is not used anymore ?

It is, it's already in the `$page['filelocation']` (has previously been removed and then readded).

**Comment by nitriques** [comment]
Oh ok great then.

**Comment by brendo** [comment]
> Even with nested dev environment inside WAMP/XAMPP? i.e. http:\localhost\wamp\sym26/workspace/pages/page.xsl

If this can be confirmed this can be merged.

**Comment by nitriques** [comment]
> If this can be confirmed this can be merged.

What do you mean ?

**Pull request merged**
