### PR TITLE
Add the possibility to run with E_ALL

### LINKED ISSUE #2674: Make error_reporting configurable
As proposed in #2673

Should it only be a "script_php" bool ?

### PR DESCRIPTION
**Pull request by nitriques**
This will make it easier to have strict setups

Fixes #2674

### CODE REVIEW

**Comment by nitriques** [comment]
> Now all we need is someone who wants to fix all the quirks by actually enabling this! :-)

I hope some people won't be able to resist in doing so ;)

**Comment by brendo** [comment]
Instead of a bool, what if the config was the actual error reporting value, eg `E_ALL`?

**Comment by nitriques** [comment]
@brendo see https://github.com/symphonycms/symphony-2/issues/2674#issuecomment-303660480

I agreed that nothing more was needed.

**Comment by nitriques** [comment]
The problem with it is that you'll loose the PHP constant when the config.php file is written. But yeah, feel free to send a PR :)

**Pull request merged**
