### PR TITLE
Remove parameters as arguments

### LINKED ISSUE #2338: Parameters as arguments (using $param in XSLT without declaring it) should be removed
There has been a [discussion about best practice](https://github.com/symphonycms/symphony-2/issues/2141) in XSLT templating regarding parameters some time ago. In this discussion, @allen [explained](https://github.com/symphonycms/symphony-2/issues/2141#issuecomment-50145118) the technical concepts and [suggested to remove "parameters as arguments"](https://github.com/symphonycms/symphony-2/issues/2141#issuecomment-50146270) from Symphony.

I am all for it. Clean that stuff up, finally. Removing `$param` type parameters will, of course, break XSLT stylesheets that do not yet adhere to the "good practice", but developers can fix this easily.

Related: https://github.com/symphonycms/symphony-2/issues/2332#issuecomment-72176600

### PR DESCRIPTION
**Pull request by nitriques**
i.e. using $param in XSLT without declaring it.

Fixes #2338

### CODE REVIEW

**Comment by michael-e** [comment]
Wow, this is a major change. Have you tested this? Should I? (From looking at the code it's impossible for me to see what can happen.)

**Comment by nitriques** [comment]
> Have you tested this?

Yes I have. I've also made lots of find in folder to make sure the methods that got removed were not used anymore.

> Should I?

Yes, you always should if you can ! ;) 

> From looking at the code it's impossible for me to see what can happen.

Does it helps to read 0614ff5's commit message ?

**Comment by michael-e** [comment]
> Does it helps to read 0614ff5's commit message ?

It helps to understand the intention, but how could it ever reveal unplanned "side effects"? :-)

Will try and test on the weekend.

**Comment by nitriques** [comment]
> but how could it ever reveal unplanned "side effects"? :-)

Haha. I would say, let's try and see ! But I feel pretty confident about it since it's only a redistribution of responsibilities. And it's 3.0.0, we are allowed to break thing.

**Comment by michael-e** [comment]
If we have the time, just give me one or two days to install and test this. Will do my best.

**Comment by nitriques** [comment]
Great. Thanks.

**Comment by nitriques** [comment]
1. Yes you are right.
  - [ ] We need to open an issue and fix the problem ;)
2. Yes you are right.
  - [ ] We need to open an issue and fix the problem ;)
3. This is not true! Instead of `$context['page']->registerPHPFunction()` you would do `$context['page']->Proc->registerPHPFunction()` :) You just have to access the right object ! Does this fixes your problem ?

**Comment by michael-e** [comment]
Re 3.: Ah, I see. So I will do more testing! Unfortunately I won't find the time before Sunday. :-(

**Comment by nitriques** [comment]
No problems, I can wait until Monday !

**Comment by nitriques** [comment]
@michael-e I do not want to put any pressure, but this needs to land right after 2.7.5 is merged because I need to rebase 3.0.x. You can trust me on this, and if you ever loose a feature, I'll make sure it gets addressed.

**Comment by nitriques** [comment]
> Sorry for all the open reviews.

Not a problem.

> I noticed that with the changes in this PR, the Email Template Manager extension will cause errors when a data source gets deleted in the backend. Don't ask me why. 

I can not *not* ask why! I do not see how this can be related to data sources !!

> But will I ever be able to fix the ETM for Sym 3.0?

I am here to help if you need so. But we need to move forward.

**Comment by michael-e** [comment]
> I can not *not* ask why!

Sure, but I really can't tell. I am under pressure currently, so I don't find the time to debug this.

> I am here to help if you need so.

Thanks!

> But we need to move forward.

Agreed on that!

**Comment by nitriques** [comment]
Great, thanks @michael-e

**Pull request merged**
