### PR TITLE
PHP 7 compatibility

### PR DESCRIPTION
**Pull request by siimsoni**

### CODE REVIEW

**Comment by siimsoni** [comment]
I did a brief manual testing after applying these changes and there didn't appear to be any other problems with running Symphony on PHP 7.

**Comment by nitriques** [comment]
Ok thanks! I'll merge when we are ready to ;)

**Comment by nitriques** [comment]
@siimsoni 

We would need a retro-compatible way to handle this... Would checking the PHP_VERSION and create separate implementations sounds ?

**Comment by michael-e** [comment]
Why is it not retro-compatible?

**Comment by nitriques** [comment]
Well, looking at the methods, I thought PHP behavior changed.

Looking at the doc (http://php.net/manual/en/sessionhandlerinterface.write.php) nothing seems news for PHP 7.

But I guess we just implemented it wrong. I propose to merge it into 2.7.x then...

**Comment by michael-e** [comment]
We'll see what happens. :-) Without diving deep into the code, it looks more like a bugfix to me.

**Comment by nitriques** [comment]
Great then. I'll test it on 5.4 and 5.6 and try to test on PHP 7 (but I need to set it up before).

**Comment by siimsoni** [comment]
At the time of implementation I tested the changes on PHP 5.6 and on PHP 7. I am convinced there aren't any new issues introduced in this pull request. However, according to some [some sources](https://github.com/tpunt/PHP7-Reference), there may have been some issues beforehand when handling error conditions, as return value of `-1` was considered a failure, but `-1` was not considered a failure.

**Comment by nitriques** [comment]
Ok Thanks @siimsoni.

I'll test it on 5.3 (yes I know..) and if everything goes well, I'll release it in 2.7.0

**Comment by nitriques** [comment]
Well it works well on 5.3, so shipping this for 2.7.0! 
Manually merged as d2e292d and ec700e5

**Comment by pwnell** [comment]
Sorry for the dumb question - but I have just upgraded to Ubuntu 16.04 which removed php5 and installed php7.  GetSymphony did not work - I tried to fetch the 2.7.x branch her eon Github bit it showed as 2.6.7 and also did not work.  Where can I get 2.7 that works with PHP7?

**Comment by siimsoni** [comment]
This has already been merged to the 2.7 branch (https://github.com/symphonycms/symphony-2/archive/2.7.x.zip), but apparently there are more issues with PHP 7. Unfortunately I don't have any complex setups in hand at the moment, so I haven't been able to test all of those. If you ping me on [Gitter](https://gitter.im/symphonycms/symphony-2), then me or someone else is probably going to be able to help you in your specific case.

**Comment by nitriques** [comment]
This has already been merged to the 2.7 branch

[Sorry, but no!](https://github.com/symphonycms/symphony-2/compare/2.7.x...0abd840) I still have not found time to test it sadly.

**Comment by pwnell** [comment]
I will test it for you... I have rolled back my Ubuntu 16.04 and am building a clean dev version so that I may test my site on it.  I will report back here. Take note that I am also running now on MySQL 5.7 (in dev - testing).

**Comment by nitriques** [comment]
@pwnell Great! MySQL 5.7 must work. We need to support 5.5, 5.6 and 5.7 ATM.

**Comment by pwnell** [comment]
I applied the 2.7 branch code to my site (upgrading from 2.6.7).  On Ubuntu 16.04 with PHP7 and MySQL 5.7 I get this when trying to access my site:

```
Symphony Fatal Error: Uncaught TypeError: Argument 1 passed to GenericExceptionHandler::handler() must be an instance of Exception, instance of Error given in /var/www/mywebsite/symphony/lib/core/class.errorhandler.php:76 Stack trace: #0 [internal function]: GenericExceptionHandler::handler(Object(Error)) #1 {main} thrown
An error occurred in /var/www/mywebsite/symphony/lib/core/class.errorhandler.php around line 76
```

**Comment by pwnell** [comment]
So above problems can be temporarily worked around by refactoring Exception in the method signatures of a couple of functions to Throwable (I presume PHP7 deprecated Exception in favour of Throwable).  That got me past this error and on to the next:

`loadXML():
    xmlParseEntityRef: no name in Entity, line: 74
    /var/www/mywebsite/symphony/lib/toolkit/class.xsltprocess.php:141`

**Comment by pwnell** [comment]
Any idea how I can move past above error?

**Comment by nitriques** [comment]
I seriously do not know. It does not looks like a PHP7 issue yo me (looks more like a data problem) ..

Also, would you mind to send a PR on the 2.7.x branch containing the fix for Error ? Thanks.

**Comment by pwnell** [comment]
I would not call it a fix as much as a temporary workaround.  I have not worked on the getsymphony code before and am uncomfortable proposing my solution as a fix, as I am unsure as to the impact the changes has on PHP5.  

Any tips how I can debug my issue further?  I cannot get to the backend as I get a different error then:

```
Declaration of extension_subsectionmanager::update($previousVersion) should be compatible with Extension::update($previousVersion = false)
An error occurred in /var/www/www.mywebsite.com/extensions/subsectionmanager/extension.driver.php around line 9
 @package subsectionmanager
5      */
6     /**
7      * Subsection Manager Extension
8      */
9     Class extension_subsectionmanager extends Extension {
10
11         /**
12          * Storage for subsection entries
13          */
```

**Comment by nitriques** [comment]
subsectionmanager is not maintained anymore. You should consider using the association_* extensions of the entry relationship field.

That being said, you should add the default parameter value, i.e. ` = false` to the signature of the update function in the extension.driver.php file of the subsectionmanager extension.

**Comment by pwnell** [comment]
I have (for now) done some fiddling with the incompatible method definitions and got to this error:

```
Expression #1 of ORDER BY clause is not in SELECT list, references column 'symphony.s.sortorder' which is not in SELECT list; this is incompatible with DISTINCT

SELECT SQL_CACHE DISTINCT (s.id), f.id as `field_id` FROM `sym_sections` AS `s` LEFT JOIN `sym_fields` AS `f` ON `s`.id = `f`.parent_section WHERE `f`.id IN ('48') ORDER BY s.sortorder ASC

[/var/www/www.mywebsite.com/symphony/lib/toolkit/class.mysql.php:554]
    MySQL->__error();
[/var/www/www.mywebsite.com/symphony/lib/toolkit/class.mysql.php:770]
    MySQL->query();
[/var/www/www.mywebsite.com/extensions/selectbox_link_field/fields/field.selectbox_link.php:107]
    MySQL->fetch();
```

**Comment by pwnell** [comment]
I think I got it to work for now... But it is a hack.  I would love to see a proper compatibility fix for the MySQL 5.7 ANSI compliance issue and the Exceptions.

**Comment by nitriques** [comment]
> But it is a hack. I would love to see a proper compatibility fix for the MySQL 5.7 ANSI compliance issue and the Exceptions.

Boy me too! I hope to be able to fix this soon enough. @jonmifsud The `order by clause not in select` error has been fixed in the core right ?

**Comment by nitriques** [comment]
> Expression #1 of ORDER BY clause is not in

Fixed in 52db3c9. @jonmifsud can you please review ? Thanks guys.

**Comment by pwnell** [comment]
This same bug is also in symphony/lib/toolkit/data-sources/class.datasource.navigation.php

``$pages = Symphony::Database()->fetch(sprintf(
            "SELECT DISTINCT p.id, p.title, p.handle, (SELECT COUNT(id) FROM `tbl_pages` WHERE parent = p.id) AS children
            FROM `tbl_pages` AS p
            LEFT JOIN `tbl_pages_types` AS pt ON (p.id = pt.page_id)
            WHERE 1 = 1
            %s
            %s
            ORDER BY p.`sortorder` ASC",
            // Add Parent SQL
            !is_null($parent_sql) ? $parent_sql : " AND p.parent IS null ",
            // Add Types SQL
            !is_null($type_sql) ? $type_sql : ""
        ));
``

**Comment by pwnell** [comment]
This same bug is also in symphony/lib/toolkit/data-sources/class.datasource.navigation.php

`$pages = Symphony::Database()->fetch(sprintf(
            "SELECT DISTINCT p.id, p.title, p.handle, (SELECT COUNT(id) FROM `tbl_pages` WHERE parent = p.id) AS children
            FROM `tbl_pages` AS p
            LEFT JOIN `tbl_pages_types` AS pt ON (p.id = pt.page_id)
            WHERE 1 = 1
            %s
            %s
            ORDER BY p.`sortorder` ASC",
            // Add Parent SQL
            !is_null($parent_sql) ? $parent_sql : " AND p.parent IS null ",
            // Add Types SQL
            !is_null($type_sql) ? $type_sql : ""
        ));
`

**Comment by nitriques** [comment]
Ok thanks. Wanna send a PR ?

**Comment by pwnell** [comment]
My symphony is installed via the ZIP file - not via git.

**Comment by nitriques** [comment]
Oh.

**Comment by nitriques** [comment]
I am currently setting up a machine with PHP7. More news to come

**Comment by DavidOliver** [comment]
Hi @nitriques. Do you know if 2.7 will be PHP 7 compatible?

**Comment by nitriques** [comment]
I sure hope so, but extensions might not.

**Comment by pwnell** [comment]
@nitriques I would like to send you a PR for class.datasource.navigation.php but do not want to mess up the GIT repository.  Can you explain how I can do that - I am used to SVN so I do not know GIT well.  I have done a 

git clone -b 2.7.x --single-branch https://github.com/symphonycms/symphony-2.git

but not sure how to proceed now?  Do I need to create a new branch:

git checkout -b fix-mysql-ansi 2.7.x

Make the code changes, then do:

git push origin fix-mysql-ansi

Then use GIT PR, pick as base branch 2.7.x, head branch as fix-mysql-ansi and click create?

**Comment by brendo** [comment]
@pwnell Yep, you've got it :)

After you make the code changes you'll need to stage, and then commit them:

1. `git add /path/to/file`
2. `git commit -m "Your commit message"

You can do this in one step, `git commit -am "Your commit message"`, but this will include any untracked changes which is sometimes undesirable.

**Comment by pwnell** [comment]
Ok all that is done, but when I try to push the change I get this:

remote: Invalid username or password.
fatal: Authentication failed for 'https://github.com/symphonycms/symphony-2.git/'

Do I need to have permission to the getsymphony git repository?  My GIT credentials alone does not seem to work for pushing changes.  Sorry if this is basic.

**Comment by brendo** [comment]
Ah, yeah you'll first need to fork your repo. Github has a helpful [guide] on how to do this!

**Comment by pwnell** [comment]
Thanks for your help! I think I got it.  PR #2648.

**Pull request merged**
