### PR TITLE
[2.7.0-RC1] Fix associations!

### PR DESCRIPTION
**Pull request by nitriques**
This PR includes all the work remaining regarding associations for 2.7.0.

It includes commits from #2698 and #2720, so those PR are gonna get closed.

@twiro @nilshoerrmann I've addressed your comments, one commit at the time. Please check the commit messages.

### CODE REVIEW

**Comment by nitriques** [comment]
@brendo no problem ;) Thanks!

**Comment by jensscherbl** [comment]
Will test and review tomorrow evening.

**Comment by nitriques** [comment]
Thanks @jensscherbl

**Comment by nilshoerrmann** [comment]
I won't have time for a review either.

**Comment by nitriques** [comment]
> Symphony’s assets are not up-to-date in this PR. 

I try not to include the build files in PR because they are prone to conflicts when doing rebase.

**Comment by jensscherbl** [comment]
> I try not to include the build files in PR because they are prone to conflicts when doing rebase.

Alright then. After testing and having a quick look at the commits, I think the PR is good to be merged.

However, I think it’s better to avoid meaningless variables like `$a` etc. in the future, makes the codebase only harder to read and understand.

**Pull request merged**
