### PR TITLE
Check if SESSION is actually an array before trying to loop over it

### PR DESCRIPTION
**Pull request by pointybeard**
See issue #2386 for details

### CODE REVIEW

**Comment by pointybeard** [comment]
yeah, this was already fixed. Good idea to check integration first eh? ;)

https://github.com/symphonycms/symphony-2/issues/2107

**Comment by michael-e** [comment]
> Good idea to check integration first eh?

AFAIK, the fix is in the 2.6.x branch. Am I right?

**Comment by pointybeard** [comment]
Hmm, [nope](https://github.com/symphonycms/symphony-2/blob/master/symphony/lib/boot/func.utilities.php#L193). It's only in integration, hence why I missed it.

**Comment by pointybeard** [comment]
Ah yes, you are right. I've been tracking master.

**Pull request closed without merging**
