### PR TITLE
Removed the 'date' column from the date field table

### PR DESCRIPTION
**Pull request by psychoticmeow**
Fixes issue #2361.

### CODE REVIEW

**Comment by brendo** [comment]
I just can't help but feel we're doing it wrong by using the text value. Anyone else? I don't really have anything to justify it other than a gut feeling :confused:

**Comment by michael-e** [comment]
Looking at the PR, I assume that Symphony uses the text value exclusively? But why? There might be reasons for this. Maybe @nilshoerrmann knows more, because he has worked a lot on date and time stuff.

Indeed it feels a bit strange. Unfortunately I don't know anything about the benfits and shortcomings of `DATETIME` values in MySQL. Anyway this change should be discussed. There should only be one of these two columns left, I think everybody agrees on that.

Last but not least: AFAIK, there has not been a final decision on a possible upgrade path from Symphony 2 to Symphony 3. (Correct me if I am wrong.) As long as we have the chance to provide an upgrade, shouldn't structural changes to the database be replicated in the updater, too?

**Comment by nitriques** [comment]
@michael-e

Using string was the only way to "remove" timezones...

>  AFAIK, there has not been a final decision on a possible upgrade path from Symphony 2 to Symphony 3.

See https://github.com/symphonycms/symphony-2/issues/2373

**Comment by nitriques** [comment]
Merged as 1377797

**Pull request closed without merging**
