### PR TITLE
Escape all commas in filtering suggestions.

### LINKED ISSUE #2349: New filter interface: Filtering on values containing commas returns no results
Using the new entry filters (integration branch), filtering on values containing commas always returns no results. It works fine for values without commas.

### PR DESCRIPTION
**Pull request by michael-e**
The previous fix replaced the first comma only.

Fixes #2349.

### CODE REVIEW

**Comment by nitriques** [comment]
I would use a regular expression in order to replace ALL of them. ?

```js
input.val(value.replace(/,/g, '\\,'));
```

Which one *is* better ?? :smile:

**Comment by michael-e** [comment]
I don't know which one is _better_, but isn't regex slower, most of the time? (And the regex `g` modifier didn't work in my quick test, don't ask me why.)

**Comment by nitriques** [comment]
> And the regex g modifier didn't work in my quick test

Is the value multiline ?

**Comment by michael-e** [comment]
No, I don't htink so.

**Comment by nitriques** [comment]
I get

```js
var value = 'test1,test2,test3';
value.replace(/,/g, '\\,'));
"test1\,test2\,test3"
```

You're in Safari ?

**Comment by nitriques** [comment]
But it looks likes it's only a tiny-tiny bit faster. http://jsperf.com/regexp-vs-split-join Leave it with split...

**Comment by michael-e** [comment]
Your test code works fine in the Safari console. Let's see what @brendo thinks.

**Comment by nitriques** [comment]
Yup.

**Comment by brendo** [comment]
Happy with the perf option, thanks @michael-e

**Pull request merged**
