### PR TITLE
ASSETS_URL constant

### PR DESCRIPTION
**Pull request by designermonkey**
I've done a thorough search through the code, but may have missed something.

As and when I find parts of the core that fail in my custom structure, I will send more PRs.

### CODE REVIEW

**Comment by designermonkey** [comment]
PS, this is untested as I've just copied across what I've done in my custom structure, which works fine with these changes.

**Comment by nitriques** [comment]
All my ad-hoc tests seems to run fine with your modifications. I think this is good to merged.

Thanks John!

**Comment by brendo** [comment]
I won't pull just yet as I want to test 0e47535 in particular. I have a bad feeling that those constants are not available during install (or didn't use to be, autoloading might of changed this)

**Comment by nitriques** [comment]
Ok Brendan, feel free to ask me anything if you need help.

**Comment by designermonkey** [comment]
When I say not tested, I meant this particular commit, the installer works fine, as I've installed using it.

**Comment by brendo** [comment]
Thanks John :)

**Pull request merged**
