### PR TITLE
XSL import fix for both Unix and windows

### PR DESCRIPTION
**Pull request by koolaid1551**
Add file protocol and replace spaces with `%20` to avoid errors on windows

This fixes https://github.com/symphonycms/symphony-2/issues/2375

### CODE REVIEW

**Comment by michael-e** [comment]
Why have you dropped the first line, `<?xml version="1.0" encoding="UTF-8"?>`?

**Comment by koolaid1551** [comment]
It was removed because I was testing @jensscherbl pull request https://github.com/symphonycms/symphony-2/pull/2376 

I have added the encoding back in and tested it on windows and linux, everything is still working.

**Comment by michael-e** [comment]
Thanks a lot! Regarding the protocol and the replacement, I hope that others can take a look.

**Comment by nitriques** [comment]
I'll test this on my linux box ASAP.

**Comment by jensscherbl** [comment]
> Why have you dropped the first line, <?xml version="1.0" encoding="UTF-8"?>?

I left it out because it's optional and our values are the default values anyway (version 1.0 and UTF-8 are assumed if the declaration is missing).

Re-added the declaration in my latest commit (to avoid further debate ;).

**Comment by nitriques** [comment]
#2376 Looks good (on Ubuntu). Do we still need this one ?

**Comment by koolaid1551** [comment]
@nitriques https://github.com/symphonycms/symphony-2/pull/2376 now works on windows as well, so this pull request can be closed

**Comment by nitriques** [comment]
@koolaid1551 Ok great! Thanks a lot for your feedback and contribution!

**Pull request closed without merging**
